pipeline {
    agent any
    
    stages {
        stage('Setup Maven') {
            steps {
                 sh '''
                 if [ ! -d maven ]; then
                     curl -s https://downloads.apache.org/maven/maven-3/3.9.11/binaries/apache-maven-3.9.11-bin.tar.gz | tar xz
                     mv apache-maven-3.9.11 maven
                    fi
                    '''
                }
        }
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') { 
            steps {
                sh './jenkins/scripts/deliver.sh' 
            }
        }
    }
}
